# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [3]:
s="Hi there Sam"
x=s.split()
print(x)

['Hi', 'there', 'Sam']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [5]:
x="The diameter of {planet} is {diameter} kilometers.".format(planet="Earth",diameter="12742")
print(x)

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [11]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
import numpy as np
array=np.zeros(10)
print ("An aray of 10 zeros")
print(array)

An aray of 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives")
print(array)

An array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [14]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all even integers from 20 to 35")
print(array)

Array of all even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [19]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [36]:
import pandas as pd
data={"A":[10,20,30],"B":[40,50,60]}
df=pd.DataFrame(data)
print(df)

    A   B
0  10  40
1  20  50
2  30  60


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
x=pd.date_range(start ='1-1-2023',end ='10-2-2023', freq='5H')
for val in x:
  print(val)


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [1]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [42]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists,columns=['s.no','name','age'])
print(df)

   s.no name  age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
